name: Update AJAY Naukri Resume

on:
  schedule:
    - cron: '0 */6 * * *' # Run 3 times a day:)
  workflow_dispatch:

jobs:
  upload-resume:
    runs-on: naukri-ec2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload resume to Naukri for Profile1
        # Use ./ format for local actions with act
        uses: Prateek-Wayne/naukri-resume-action@v1.2.0
        with:
          username: ${{ secrets.AJAY_NAUKRI_EMAIL }}
          password: ${{ secrets.AJAY_NAUKRI_PASSWORD }}
          profile_id: ${{ secrets.AJAY_PROFILE_ID }}
          resume_path: |-
            ./resumes/SDE_Resume_Ajay_Full_Stack.pdf
          profile_summary: "Full-Stack Developer with hands-on experience in building scalable and high-performance web applications using React.js, Next.js, Flask, Node.js, JavaScript, and TypeScript. 
                            Skilled in RESTful API design, JWT authentication, backend architecture, and scalable backend services with experience in MongoDB, PostgreSQL, Redis, and SQLAlchemy.
                            Worked on scalable onboarding platforms, real-time monitoring systems, and micro frontend applications at Philips Healthcare. 
                            Improved application modularity, backend workflows, data aggregation, and system performance through optimized frontend and backend development.
                            Strong understanding of Data Structures, Algorithms, OOP, and DBMS with 800+ DSA problems solved on LeetCode and a Knight badge rating of 1914.
                            Looking for Full-Stack Developer, Backend Developer, and Software Development Engineer roles."
