name: Update AJAY Naukri Resume

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight :)
  workflow_dispatch:

jobs:
  upload-resume:
    runs-on: naukri-ec2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload resume to Naukri for Profile1
        # Use ./ format for local actions with act
        uses: Prateek-Wayne/naukri-resume-action@v1.0.1
        with:
          username: ${{ secrets.HARKIRAT_NAUKRI_EMAIL }}
          password: ${{ secrets.HARKIRAT_NAUKRI_PASSWORD }}
          profile_id: ${{ secrets.HARKIRAT_PROFILE_ID }}
          resume_path: |-
            ./resumes/Harkirat_Singh.pdf
