name: Update Naukri Resume for ProfileMAIN

on:
  schedule:
    # 8:13 AM IST → 10:13 PM IST every 2 hours
    - cron: '43 2 * * *'   # 8:13 AM
    - cron: '43 4 * * *'   # 10:13 AM
    - cron: '43 6 * * *'   # 12:13 PM
    - cron: '43 8 * * *'   # 2:13 PM
    - cron: '43 10 * * *'  # 4:13 PM
    - cron: '43 12 * * *'  # 6:13 PM
    - cron: '43 14 * * *'  # 8:13 PM
    - cron: '43 16 * * *'  # 10:13 PM

  workflow_dispatch:

jobs:
  upload-resume:
    runs-on: naukri-ec2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload resume to Naukri for Profile1
        uses: Prateek-Wayne/naukri-resume-action@v1.2.0
        with:
          username: ${{ secrets.NAUKRI_USERNAME_MAIN }}
          password: ${{ secrets.NAUKRI_PASSWORD_MAIN }}
          profile_id: ${{ secrets.NAUKRI_PROFILE_ID_MAIN }}
          resume_path: |-
            ./resumes/PRATEEK_RESUME.pdf
          profile_summary: "Software Development Engineer with ~3 years of experience at Philips, working on building scalable, cloud-native applications and backend systems. Experienced in developing and optimizing REST APIs, working with microservices architecture, and improving system performance through caching, query optimization, and efficient design.
                            Proficient in Java, Spring Boot, Node.js, and TypeScript, with hands-on experience in AWS (EKS, EC2, S3, Secrets Manager), Kubernetes, Docker, and CI/CD pipelines. Strong understanding of distributed systems, observability (OpenTelemetry, Prometheus, Grafana), and production-grade system design.
                            Passionate about solving problems related to scalability, performance, and reliability. Currently seeking opportunities in backend or full stack development roles where I can contribute to building high-impact systems and continue growing as an engineer."
